// src/cangzhen/pages/Review.jsx
import React from 'react';

const Review = () => {
  return (
    <div className="min-h-screen relative p-6 font-serif flex flex-col">
      <header className="mb-8">
        <h1 className="text-3xl font-medium text-cangzhen-text-main">回顾</h1>
        <p className="text-sm font-italic text-cangzhen-text-secondary italic tracking-wider">Weekly & Monthly Review</p>
      </header>

      <div className="space-y-6">
        {/* 1. 周回顾 · 玻璃信笺 */}
        <div className="glass p-6 relative overflow-hidden group">
            <div className="absolute top-0 right-0 p-4 opacity-10">
                <span className="text-6xl font-serif">W</span>
            </div>
            <h3 className="text-lg font-medium text-cangzhen-text-main mb-4">本周 · 玻璃信笺</h3>
            <p className="text-sm text-cangzhen-text-main/80 leading-relaxed mb-4 font-serif">
                "这一周的雨水很多，但你的心里似乎藏着一个小太阳。"
            </p>
            
            <div className="space-y-3 mb-6">
                <div className="glass-concave p-3 flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-cangzhen-sensation-main mt-1.5 shrink-0" />
                    <p className="text-xs text-cangzhen-text-secondary">
                        <span className="text-cangzhen-text-main font-medium">感知高光：</span>
                        清晨的雨声，滴答滴答...
                    </p>
                </div>
                <div className="glass-concave p-3 flex items-start gap-3">
                    <span className="w-1.5 h-1.5 rounded-full bg-cangzhen-emotion-main mt-1.5 shrink-0" />
                    <p className="text-xs text-cangzhen-text-secondary">
                        <span className="text-cangzhen-text-main font-medium">情绪波动：</span>
                        听到那首歌，突然很想哭。
                    </p>
                </div>
            </div>

            <div className="flex justify-between items-end">
                <p className="text-xs text-cangzhen-text-secondary italic">
                    Generated by AI · March 8
                </p>
                <button className="glass-convex px-4 py-1.5 text-xs">查看详情</button>
            </div>
        </div>

        {/* 2. 月回顾 · 花册 */}
        <div className="glass p-6 relative overflow-hidden">
             <div className="absolute top-0 right-0 p-4 opacity-10">
                <span className="text-6xl font-serif">M</span>
            </div>
            <h3 className="text-lg font-medium text-cangzhen-text-main mb-4">二月 · 花册</h3>
            
            <div className="grid grid-cols-2 gap-4 mb-4">
                <div className="glass-concave p-3 flex flex-col items-center justify-center aspect-square">
                    <span className="text-2xl font-medium text-cangzhen-text-main">28</span>
                    <span className="text-[10px] text-cangzhen-text-secondary uppercase">Memories</span>
                </div>
                <div className="glass-concave p-3 flex flex-col items-center justify-center aspect-square">
                    <span className="text-2xl font-medium text-cangzhen-text-main">Top 1</span>
                    <span className="text-[10px] text-cangzhen-text-secondary uppercase">Emotion</span>
                </div>
            </div>
            
            <button className="w-full glass-convex py-3 text-xs">翻阅花册</button>
        </div>

        {/* 3. 年度回顾 (Placeholder) */}
        <div className="glass-concave p-8 flex flex-col items-center justify-center text-center opacity-60">
            <span className="text-4xl mb-2 opacity-50">⏳</span>
            <h3 className="text-sm font-medium text-cangzhen-text-main mb-1">年度回顾</h3>
            <p className="text-xs text-cangzhen-text-secondary italic">Available in December 2026</p>
        </div>
      </div>
    </div>
  );
};

export default Review;
